/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated/timetable'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSchoolRouteImport } from './routes/_authenticated/school'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedTeachersIndexRouteImport } from './routes/_authenticated/teachers/index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedResultsIndexRouteImport } from './routes/_authenticated/results/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedTeachersNewRouteImport } from './routes/_authenticated/teachers/new'
import { Route as AuthenticatedTeachersIdRouteImport } from './routes/_authenticated/teachers/$id'
import { Route as AuthenticatedStudentsNewRouteImport } from './routes/_authenticated/students/new'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students/$id'
import { Route as AuthenticatedDashboardRoleRouteImport } from './routes/_authenticated/dashboard.$role'
import { Route as AuthenticatedResultsReportStudentIdRouteImport } from './routes/_authenticated/results/report.$studentId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolRoute = AuthenticatedSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachersIndexRoute =
  AuthenticatedTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsIndexRoute =
  AuthenticatedResultsIndexRouteImport.update({
    id: '/results/',
    path: '/results/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersNewRoute =
  AuthenticatedTeachersNewRouteImport.update({
    id: '/teachers/new',
    path: '/teachers/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachersIdRoute = AuthenticatedTeachersIdRouteImport.update({
  id: '/teachers/$id',
  path: '/teachers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsNewRoute =
  AuthenticatedStudentsNewRouteImport.update({
    id: '/students/new',
    path: '/students/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoleRoute =
  AuthenticatedDashboardRoleRouteImport.update({
    id: '/dashboard/$role',
    path: '/dashboard/$role',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsReportStudentIdRoute =
  AuthenticatedResultsReportStudentIdRouteImport.update({
    id: '/results/report/$studentId',
    path: '/results/report/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/school': typeof AuthenticatedSchoolRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/dashboard/$role': typeof AuthenticatedDashboardRoleRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/teachers/$id': typeof AuthenticatedTeachersIdRoute
  '/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/results/': typeof AuthenticatedResultsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/results/report/$studentId': typeof AuthenticatedResultsReportStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/school': typeof AuthenticatedSchoolRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/dashboard/$role': typeof AuthenticatedDashboardRoleRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/teachers/$id': typeof AuthenticatedTeachersIdRoute
  '/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/results': typeof AuthenticatedResultsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
  '/results/report/$studentId': typeof AuthenticatedResultsReportStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/school': typeof AuthenticatedSchoolRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
  '/_authenticated/dashboard/$role': typeof AuthenticatedDashboardRoleRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/students/new': typeof AuthenticatedStudentsNewRoute
  '/_authenticated/teachers/$id': typeof AuthenticatedTeachersIdRoute
  '/_authenticated/teachers/new': typeof AuthenticatedTeachersNewRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/results/': typeof AuthenticatedResultsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/_authenticated/results/report/$studentId': typeof AuthenticatedResultsReportStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/recover'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/attendance'
    | '/finance'
    | '/profile'
    | '/school'
    | '/settings'
    | '/timetable'
    | '/dashboard/$role'
    | '/students/$id'
    | '/students/new'
    | '/teachers/$id'
    | '/teachers/new'
    | '/dashboard/'
    | '/results/'
    | '/students/'
    | '/teachers/'
    | '/results/report/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/recover'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/attendance'
    | '/finance'
    | '/profile'
    | '/school'
    | '/settings'
    | '/timetable'
    | '/dashboard/$role'
    | '/students/$id'
    | '/students/new'
    | '/teachers/$id'
    | '/teachers/new'
    | '/dashboard'
    | '/results'
    | '/students'
    | '/teachers'
    | '/results/report/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/recover'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/_authenticated/attendance'
    | '/_authenticated/finance'
    | '/_authenticated/profile'
    | '/_authenticated/school'
    | '/_authenticated/settings'
    | '/_authenticated/timetable'
    | '/_authenticated/dashboard/$role'
    | '/_authenticated/students/$id'
    | '/_authenticated/students/new'
    | '/_authenticated/teachers/$id'
    | '/_authenticated/teachers/new'
    | '/_authenticated/dashboard/'
    | '/_authenticated/results/'
    | '/_authenticated/students/'
    | '/_authenticated/teachers/'
    | '/_authenticated/results/report/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RecoverRoute: typeof RecoverRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school': {
      id: '/_authenticated/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof AuthenticatedSchoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/': {
      id: '/_authenticated/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof AuthenticatedTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/': {
      id: '/_authenticated/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof AuthenticatedResultsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/new': {
      id: '/_authenticated/teachers/new'
      path: '/teachers/new'
      fullPath: '/teachers/new'
      preLoaderRoute: typeof AuthenticatedTeachersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/$id': {
      id: '/_authenticated/teachers/$id'
      path: '/teachers/$id'
      fullPath: '/teachers/$id'
      preLoaderRoute: typeof AuthenticatedTeachersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/new': {
      id: '/_authenticated/students/new'
      path: '/students/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AuthenticatedStudentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/$role': {
      id: '/_authenticated/dashboard/$role'
      path: '/dashboard/$role'
      fullPath: '/dashboard/$role'
      preLoaderRoute: typeof AuthenticatedDashboardRoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/report/$studentId': {
      id: '/_authenticated/results/report/$studentId'
      path: '/results/report/$studentId'
      fullPath: '/results/report/$studentId'
      preLoaderRoute: typeof AuthenticatedResultsReportStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSchoolRoute: typeof AuthenticatedSchoolRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
  AuthenticatedDashboardRoleRoute: typeof AuthenticatedDashboardRoleRoute
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedStudentsNewRoute: typeof AuthenticatedStudentsNewRoute
  AuthenticatedTeachersIdRoute: typeof AuthenticatedTeachersIdRoute
  AuthenticatedTeachersNewRoute: typeof AuthenticatedTeachersNewRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedResultsIndexRoute: typeof AuthenticatedResultsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedTeachersIndexRoute: typeof AuthenticatedTeachersIndexRoute
  AuthenticatedResultsReportStudentIdRoute: typeof AuthenticatedResultsReportStudentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSchoolRoute: AuthenticatedSchoolRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
  AuthenticatedDashboardRoleRoute: AuthenticatedDashboardRoleRoute,
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedStudentsNewRoute: AuthenticatedStudentsNewRoute,
  AuthenticatedTeachersIdRoute: AuthenticatedTeachersIdRoute,
  AuthenticatedTeachersNewRoute: AuthenticatedTeachersNewRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedResultsIndexRoute: AuthenticatedResultsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedTeachersIndexRoute: AuthenticatedTeachersIndexRoute,
  AuthenticatedResultsReportStudentIdRoute:
    AuthenticatedResultsReportStudentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RecoverRoute: RecoverRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
